### ISSUE TITLE
Provide a refinement function?

### ISSUE THREAD

**Issue by anthonyjoeseph** [pfgray/ts-adt#19]
This idea is for something like [morphic-ts predicates](https://github.com/sledorze/morphic-ts#predicates)

Not sure if this is desired or out of scope, but it might be handy! A possible use case could be in conjunction w/ [fp-ts-routing](https://github.com/gcanti/fp-ts-routing) - `makeRefinement` could refine groups of routes

Spec:

```ts
type Xor<A, B> = ADT<{
  nothing: {};
  left: { value: A };
  right: { value: A };
}>;

const exists = <A, B>() => refinement<Xor<A, B>>()(['left', 'right'])

declare const myXor: Xor<number, string>;

if (exists()(myXor)) {
  myXor._type // _type: "left" | "right"
  myXor.value // value: string | number
}
```

Implementation:

```ts
const makeRefinement = <TagName extends string>(
  tag: TagName
) => <ADT extends { [t in TagName]: string }>() => <Tag extends ADT[TagName]>(
  tags: readonly Tag[]
) => (
  s: ADT
): s is Extract<ADT, { [t in TagName]: Tag }> =>
  tags.includes(s[tag] as string as Tag)

const refinement = makeRefinement('_type')
```

**Comment by pfgray** [comment]
@anthonyjoeseph, I really like this idea, however I'm wondering if we rearrange the type parameters, it might make it even easier to use (i.e. you don't have to supply a type parameter):

```ts
const makeRefinement = <TagName extends string>(
  tag: TagName
) => <Tag extends string>(
  tags: readonly Tag[]
) => <ADT extends { [t in TagName]: string }>(
  s: ADT
): s is Extract<ADT, { [t in TagName]: Tag }> =>
  tags.includes(s[tag])

const refinement = makeRefinement('_type')

declare const myXor: Xor<number, string>;

if (refinement(['left', 'right'])(myXor)) { // no type params
  myXor._type // _type: "left" | "right"
  myXor.value // value: string | number
}
```

what do you think?

**Comment by anthonyjoeseph** [comment]
I love it! I added another feature that causes a type error if any of the refinement tags are misspelled - it's a bit messy, but (I think) it works

[playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBDAnmApnA3nAggEQCpwC+cAZlBCHAOQwDOAtAIYAmMVAUO0qnABrQAeLABo4AIQB8cALzZ8A9OzhwAdhBgALYCoDmALgyEA3ErgAbFCRgHMAN0ZmArigNYiJ5VGA6N1jHHsnF3F3dkIJEy5kNABhCBUYRm1aLBgAGRRGWhghUUkZEJQADxgUFWZabDgAfgQoZzgDEgdaFE4AY3jsuBBGAGsUACVLbRQQMvhZATxGHQA5RnG4YtLyyuyvXQkAClNE-TgZ+cW2gEoZKWnZ5ZKyirgN7R0dvdnaAyhM5nizREPZgDaAF12OdpJdcAQVndKpgAfBtP9juMgQZHroiC9lO84HEEkkVCl0plskJ8ACjgsUaIjlJoWs6g1apDGqoULYUFBQWi4MBKgBREpQRjtHKmZR4xLJVIZLI5SEU2ZUlBAmmzOm3BkwepoZn4Vkqdmc0Ti-zw3kqJHK1FIoimKTghBvAB02naTmYKFo21o8NmQLgWQe2qegcqR1OHS68E+JFG4wSBV6A2GccNCZg2yoAH1uCgqJH2J73YxPnBOoT4CBEPwoAZawIVI4QAAjY3BzbPSLAEhwbax+MTbYAqgWKxUURULw+NhA07bau107nTAAelXqggCGicDApcWtFMi+gztzO-XcDPqAMACIxzAb3AAD5wG-T3w3o81k+BBoX3-BOiOjPqozZtlyhCcBeygwbBcHwQhcEgHytCoGYFjMOw0GIThuE4bY7AVt0eb8lA5BQAUA7pkOI73hO1DTrO87HlA5wXgI9D0NuPCcuR7BAA)

It looks great as it is, though, if you'd rather just keep it simple

**Comment by anthonyjoeseph** [comment]
Would you mind if I made a PR for this?

**Comment by pfgray** [comment]
@anthonyjoeseph , No, go right ahead
