### ISSUE TITLE
Cannot install ts-adt

### ISSUE THREAD

**Issue by not-rusty** [pfgray/ts-adt#31]
I don't know why exactly, but a fresh install in my Ubuntu 20 cannot make use of your library.

Node version: 14.16.0
npm version: 6.14.13

Commands followed:
`$ npm init -y`
`$ npm install ts-adt` 

Error:

`Cannot find module 'ts-adt' or its corresponding type declarations`

Maybe it is something to do with the main entry in the package.json? No idea.

**Comment by pfgray** [comment]
Ok, looks like I bundled the `2.1.0` version, and in my attempt to fix it, also the `2.1.1` version, but `2.1.2` should work :) try re-installing, thanks for the report, and sorry for the inconvenience!
